import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, random_split
import matplotlib.pyplot as plt
import numpy as np

# ─────────────────────────────────────────────
# 1. Dataset
# ─────────────────────────────────────────────

class BezierDataset(Dataset):
    """
    Loads the dataset generated by generate_dataset.py.
    Each sample contains:
        - X                    : cloud of points (100, 2)
        - initial_control_points : Pc used as initialisation (6, 2)
        - final_control_points   : Popt after optimisation (6, 2)  ← training target
    """
    def __init__(self, path="dataset/dataset.pt"):
        raw = torch.load(path)
        self.X    = torch.stack([d["X"]                    for d in raw])  # (N, 100, 2)
        self.Pc   = torch.stack([d["initial_control_points"] for d in raw])  # (N, 6, 2)
        self.Popt = torch.stack([d["final_control_points"]   for d in raw])  # (N, 6, 2)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.Popt[idx]   # input, target
        # Note: we train the network to predict Popt directly.
        # The idea is that a good Pc (close to Popt) will make the
        # iterative algorithm converge faster.


# ─────────────────────────────────────────────
# 2. Model
# ─────────────────────────────────────────────

class BezierInitNet(nn.Module):
    """
    MLP that predicts initial control points Pc from a point cloud X.

    Architecture:
        input  : (batch, 100, 2)  →  flattened to (batch, 200)
        hidden : 200 → 256 → ReLU → 128 → ReLU → 64 → ReLU
        output : 64  → 12         →  reshaped to (batch, 6, 2)

    No activation on the output layer: control point coordinates are
    unbounded real numbers, so we let the network output any value.
    """
    def __init__(self, n_points: int = 100, n_control: int = 6):
        super().__init__()
        self.n_control = n_control
        self.net = nn.Sequential(
            nn.Linear(n_points * 2, 256),
            nn.ReLU(),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, n_control * 2),   # no activation here
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # x : (batch, 100, 2)
        x = x.view(x.size(0), -1)            # (batch, 200)
        out = self.net(x)                     # (batch, 12)
        return out.view(-1, self.n_control, 2)  # (batch, 6, 2)


# ─────────────────────────────────────────────
# 3. Training loop
# ─────────────────────────────────────────────

def train(
    dataset_path: str = "./datasets/dataset.pt",
    n_epochs:     int = 200,
    batch_size:   int = 16,
    lr:           float = 1e-3,
    val_split:    float = 0.2,
    save_path:    str = "./src/IA/models/model.pt",
):
    # ── data ──────────────────────────────────
    dataset = BezierDataset(dataset_path)
    n_val   = max(1, int(len(dataset) * val_split))
    n_train = len(dataset) - n_val
    train_set, val_set = random_split(dataset, [n_train, n_val])

    train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True)
    val_loader   = DataLoader(val_set,   batch_size=batch_size)

    print(f"Dataset : {len(dataset)} samples  |  train {n_train}  val {n_val}")

    # ── model, loss, optimiser ────────────────
    model     = BezierInitNet(n_points=100, n_control=6)
    n_params = sum(p.numel() for p in model.parameters())
    print(f"Model parameters: {n_params:,}")
    criterion = nn.MSELoss()          # mean squared error on control point coordinates
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)

    # ── training ──────────────────────────────
    train_losses, val_losses = [], []

    for epoch in range(1, n_epochs + 1):

        # --- train ---
        model.train()
        epoch_loss = 0.0
        for X_batch, Popt_batch in train_loader:
            optimizer.zero_grad()
            pred  = model(X_batch)            # (batch, 6, 2)
            loss  = criterion(pred, Popt_batch)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item() * len(X_batch)
        train_losses.append(epoch_loss / n_train)

        # --- validation ---
        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for X_batch, Popt_batch in val_loader:
                pred      = model(X_batch)
                val_loss += criterion(pred, Popt_batch).item() * len(X_batch)
        val_losses.append(val_loss / n_val)

        if epoch % 20 == 0 or epoch == 1:
            print(f"Epoch {epoch:4d}/{n_epochs}  "
                  f"train loss {train_losses[-1]:.6f}  "
                  f"val loss   {val_losses[-1]:.6f}")

    # ── save ──────────────────────────────────
    torch.save(model.state_dict(), save_path)
    print(f"\nModel saved to {save_path}")

    # ── plot loss curves ──────────────────────
    plt.figure(figsize=(8, 4))
    plt.plot(train_losses, label="train loss")
    plt.plot(val_losses,   label="val loss",  linestyle="--")
    plt.xlabel("epoch")
    plt.ylabel("MSE loss")
    plt.title("Training curves")
    plt.legend()
    plt.tight_layout()
    plt.savefig("./src/IA/curves_loss/loss_curves.png", dpi=150)
    plt.show()
    print("Loss curves saved to ./src/IA/curves_loss/loss_curves.png")

    return model, train_losses, val_losses


# ─────────────────────────────────────────────
# 4. Quick inference test
# ─────────────────────────────────────────────

def predict(model: BezierInitNet, X: np.ndarray) -> np.ndarray:
    """
    Predict initial control points for a single point cloud.

    Parameters
    ----------
    model : trained BezierInitNet
    X     : numpy array of shape (100, 2)

    Returns
    -------
    Pc_pred : numpy array of shape (6, 2)
    """
    model.eval()
    with torch.no_grad():
        x_t   = torch.tensor(X, dtype=torch.float32).unsqueeze(0)  # (1, 100, 2)
        pred  = model(x_t)                                          # (1, 6, 2)
    return pred.squeeze(0).numpy()                                  # (6, 2)


# ─────────────────────────────────────────────
# 5. Entry point
# ─────────────────────────────────────────────

if __name__ == "__main__":
    model, train_losses, val_losses = train(
        dataset_path = "./src/IA/datasets/dataset.pt",
        n_epochs     = 100,
        batch_size   = 10,
        lr           = 1e-3,
        val_split    = 0.2,
        save_path    = "./src/IA/models/test.pt",
    )